runtime: nodejs16
env: standard
instance_class: F2
service_account: skinhealth-sa-deploy-app@cp-gaa-dev-skin-health.iam.gserviceaccount.com
inbound_services:
  - warmup
handlers:
  - url: /_ah/warmup
    script: auto
    secure: always