runtime: nodejs16
env: standard
service: pca-skin
instance_class: F2
service_account: skinhealth-sa-deploy-app@cp-gaa-dev-skin-health.iam.gserviceaccount.com
inbound_services:
  - warmup
handlers:
  - url: /_ah/warmup
    script: auto
    secure: always
  - url: /
    static_files: build/index.html
    upload: build/index.html
    expiration: 1s
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  # # This client ID is required to create a token to pass the IAP
  # VAULT_IAP_CLIENT_ID: '590571108011-o37jof2iadluek3dpuit5n9h8u5jldla.apps.googleusercontent.com'
  # This is the publicly accessible Vault address
  VAULT_HOST: 'https://public.vault.colpal.cloud'
  # The role this will be authenticating as within Vault. This is based on the
  # role you created in the colpal/vault repository
  VAULT_ROLE: 'skinhealth-sa-deploy-app@cp-gaa-dev-skin-health.iam.gserviceaccount.com'
  VAULT_PATH: 'secret/data/teams//skin-health-frontend/dev/pca-skin'