name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: yarn install
      - run: yarn build 
      - name: Deploy to gcloud 
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEYBASE64 }}
          service_account_email: ${{secrets.GCP_SA_EMAIL}}
      - name: Deploye
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: app.yaml
          project_id: '${{secrets.GCP_PROJECT_ID}}'
          service_account_key: '${{ secrets.GCP_SA_KEYBASE64 }}'
     




